name: cjsurf-swell-batch-predict

on:
  workflow_dispatch:
  schedule:
    - cron: '24 */6 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.1'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          BACKFILL: False
        run: ./scripts/run-swell-prediction-pipelines-every-6-hrs.sh

#      - name: update graph image with predictions
#        uses: devops-infra/action-commit-push@master
#        with:
#          github_token: "${{ secrets.GITHUB_TOKEN }}"
#          add_timestamp: true
#          commit_prefix: "[AUTO]"
#          commit_message: "Automatic commit of latest_lahinch.png"
#          force: false
#          target_branch: gh-pages

